version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: castore
    versions:
    - 0.1.9
  - dependency-name: plug_cowboy
    versions:
    - 2.4.1
  - dependency-name: mint
    versions:
    - 1.2.0
